SRCROOT=../..
SUBDIRS_MKINC= common
SUBDIRS_MKINC+= ${MACHINE}
include $(SRCROOT)/mk/mk.conf

LIBNAME= crt
LIBDIR= /lib/sys

include $(MAKEDIR)/obj.mk
include $(MAKEDIR)/lib.mk
include $(MAKEDIR)/def.mk
