SRCROOT=../..
MKDIR=$(SRCROOT)/mk
SUBDIRS_MKINC= common
SUBDIRS_MKINC+= ${MACHINE}
include $(MKDIR)/mk.conf

LIBNAME= crt
LIBDIR= /lib/sys

include $(MKDIR)/obj.mk
include $(MKDIR)/lib.mk
include $(MKDIR)/def.mk
