SRCROOT=../..
MKDIR=$(SRCROOT)/mk
include $(MKDIR)/mk.conf
include $(SRCROOT)/common/lib/misc/Makefile.inc

LIBNAME=squoze
LIBDIR=/usr/lib
SRCS+= unsquoze.c

INCS= squoze.h
INCDIR= 

include $(MKDIR)/inc.mk
include $(MKDIR)/obj.mk
include $(MKDIR)/lib.mk
include $(MKDIR)/def.mk
