SRCROOT=../..
MKDIR=$(SRCROOT)/mk
include $(MKDIR)/mk.conf

LIBNAME=squoze
LIBDIR=/usr/lib
SRCS+= squoze.c unsquoze.c

INCS= squoze.h
INCDIR= 

include $(MKDIR)/inc.mk
include $(MKDIR)/obj.mk
include $(MKDIR)/lib.mk
include $(MKDIR)/def.mk
