SRCROOT=../../..
include $(SRCROOT)/mk/mk.conf

# Public
INCS= ukparam.h
INCDIR= machine/uk

UKINCS= ansi.h asm.h cdefs.h cpu.h i386.h int_types.h apic.h locks.h	\
	machdep.h pae.h param.h platform.h pmap.h types.h ukparam.h	\
	vmparam.h tlb.h
UKINCDIR= machine/uk

include $(MAKEDIR)/inc.mk
include $(MAKEDIR)/ukinc.mk
include $(MAKEDIR)/def.mk
