SRCROOT=../../
include $(SRCROOT)/mk/mk.conf

INCS= ansi.h asm.h bswap.h byte_swap.h cdefs.h endian.h		\
	endian_machdep.h int_const.h int_fmtio.h int_limits.h	\
	int_mwgwtypes.h int_types.h limits.h param.h profile.h	\
	setjmp.h types.h vmparam.h wchar_limits.h
INCS+= mrgparam.h
INCDIR= machine

include $(MAKEDIR)/inc.mk
include $(MAKEDIR)/def.mk
