SRCROOT=../..
MKDIR=$(SRCROOT)/mk
include $(MKDIR)/mk.conf

SRCS= ahci.c

INCS= ahci.h
INCDIR= mrg/blk

LIBNAME=ahci
LIBDIR=/lib

include $(MKDIR)/inc.mk
include $(MKDIR)/obj.mk
include $(MKDIR)/lib.mk
include $(MKDIR)/def.mk
