SRCROOT=../..
include $(SRCROOT)/mk/mk.conf

INCS= ansi.h bswap.h bitops.h cdefs.h cdefs_elf.h common_int_const.h	\
	common_int_fmtio.h common_int_mwgwtypes.h common_int_limits.h	\
	common_int_types.h endian.h errno.h fd_set.h featuretest.h	\
	inttypes.h mman.h null.h param.h rbtree.h queue.h stdarg.h	\
	stdint.h syslimits.h types.h
INCS+= dirtio.h dirtio_config.h dirtio_ring.h dirtio_types.h
INCDIR= sys

include $(MAKEDIR)/inc.mk
include $(MAKEDIR)/def.mk
