SRCROOT=../..
include $(SRCROOT)/mk/mk.conf

INCS= ansi.h bswap.h cdefs.h cdefs_elf.h common_int_const.h		\
	common_int_mwgwtypes.h common_int_limits.h common_int_types.h	\
	endian.h fd_set.h featuretest.h stdarg.h stdint.h types.h
INCDIR= sys

include $(MAKEDIR)/inc.mk
include $(MAKEDIR)/def.mk
