SRCROOT=../..
include $(SRCROOT)/mk/mk.conf

# Microkernel headers
UKINCS+= uk/logio.h uk/string.h uk/setjmp.h uk/stddef.h
#From NetBSD
UKINCS+= uk/queue.h uk/rbtree.h
UKINCDIR= uk

include $(MAKEDIR)/ukinc.mk
include $(MAKEDIR)/def.mk