SRCROOT=../../../
CURDIR=i386/include
MKDIR=$(SRCROOT)/mk
include $(MKDIR)/rules.mk

INCS= ansi.h asm.h cdefs.h cpu.h int_types.h locks.h pae.h \
	param.h pmap.h types.h vmparam.h tlb.h
INCDIR= machine/uk

include $(MKDIR)/inc.mk
include $(MKDIR)/def.mk
