SRCROOT=../../..
include $(SRCROOT)/mk/mk.conf

INCS= ansi.h asm.h cdefs.h cpu.h int_types.h lapic.h locks.h pae.h \
	param.h platform.h pmap.h types.h vmparam.h sys.h tlb.h 
INCDIR= machine/uk

include $(MAKEDIR)/inc.mk
include $(MAKEDIR)/def.mk
