SRCROOT=../../../
MKDIR=$(SRCROOT)/mk
include $(MKDIR)/mk.conf

LIBNAME=vtty
LIBDIR=/usr/lib

SRCS+= consio_vtdrv.c
CFLAGS+= -I..

include ../Makefile.inc

include $(MKDIR)/inc.mk
include $(MKDIR)/obj.mk
include $(MKDIR)/lib.mk
include $(MKDIR)/def.mk
