SRCROOT=../..
MKDIR=$(SRCROOT)/mk
include $(MKDIR)/mk.conf

SRCS= part.c

INCS= part.h
INCDIR= mrg/blk

LIBNAME=part
LIBDIR=/lib

include $(MKDIR)/inc.mk
include $(MKDIR)/obj.mk
include $(MKDIR)/lib.mk
include $(MKDIR)/def.mk
