#!/bin/sh
#
# Import NetBSD source file
#
# - to be run from source root
# - nbsd/ is link to netbsd /usr/src
#
# scripts/netbsd_import <netbsd path> <our path>

echo "/* *INDENT-OFF* */ /* Imported from NetBSD -- MHDIFFIGNORE */" > $2
cat nbsd/$1 >> $2
echo $1 $2 >> scripts/netbsd_imports

