#!/bin/sh
#
# Update NetBSD imported files to a new revision of NetBSD
#
# - to be run from source root
# - nbsd/ is link to netbsd /usr/src
#
# scripts/netbsd_update

# copy original netbsd files
awk '{ system("bash -c \" install -d `dirname "$2"`; install -m 0644 nbsd/"$1" "$2" \" "); }' scripts/netbsd_imports

# patch using diff
patch -p1 < scripts/netbsd.patch

# add Imported from NetBSD line
awk '{ system("bash -c \" cat scripts/netbsd_header "$2" > /tmp/tmp.diff; cp /tmp/tmp.diff "$2" \" "); }' scripts/netbsd_imports

echo Now do a git diff and check those who changed version.
