SRCROOT=../../
MKDIR=$(SRCROOT)/mk
include $(MKDIR)/mk.conf

LIBNAME=rumpmrg
LIBDIR=/lib
CFLAGS+= -DLIBRUMPUSER
SRCS= rumpuser.c rumpuser_errtrans.c

include $(MKDIR)/obj.mk
include $(MKDIR)/lib.mk
include $(MKDIR)/def.mk
