SRCROOT=..
include $(SRCROOT)/mk/mk.conf

INCSUBDIRS= $(MACHINE) $(SRCROOT)/ukern/src \
	$(SRCROOT)/ukern/$(MACHINE)/src \
	$(SRCROOT)/sys/sys \
	$(SRCROOT)/sys/$(MACHINE)/include

include $(MAKEDIR)/inc.mk
include $(MAKEDIR)/def.mk
