SRCROOT=../../../
MKDIR=$(SRCROOT)/mk
include $(MKDIR)/mk.conf

LIBNAME=vtty_bare

LIBDIR=/usr/lib

include ../Makefile.inc

include $(MKDIR)/inc.mk
include $(MKDIR)/obj.mk
include $(MKDIR)/lib.mk
include $(MKDIR)/def.mk
