SRCROOT=../../
CURDIR=include
MKDIR=$(SRCROOT)/mk
include $(MKDIR)/rules.mk

INCS= assert.h cdefs.h cdefs_elf.h types.h locks.h param.h stdarg.h stdbool.h

#From NetBSD
INCS+= queue.h rbtree.h

INCDIR= uk
INCSUBDIRS=

include $(MKDIR)/inc.mk
include $(MKDIR)/def.mk
