SRCROOT=../../
CURDIR=include
MKDIR=$(SRCROOT)/mk

INCS= assert.h cdefs.h cdefs_elf.h types.h locks.h param.h stdarg.h

#From NetBSD
INCS+= queue.h

INCINSTDIR= uk
INCSUBDIRS=

include $(MKDIR)/includes.mk
