SRCROOT=../..
include $(SRCROOT)/mk/mk.conf

INCS= assert.h cdefs.h cdefs_elf.h types.h locks.h param.h stdarg.h stdbool.h \
	elf.h

#From NetBSD
INCS+= queue.h rbtree.h

INCDIR= uk
INCSUBDIRS=

include $(MAKEDIR)/inc.mk
include $(MAKEDIR)/def.mk
